# docker compose file for build linux devbox
version: "3"
services:
  devbox:
    container_name: linuxbox
    image: torusdev1.azurecr.io/devlinux
    # ports:
    #   - 8000-8060:8000-8060
    volumes:
      - ./:/src
      - //var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    command: /bin/bash


# az login
# az acr login --name torusdev1
# docker-compose -f linuxbox.yaml up --no-start
# docker start -i linuxbox
