POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjY0YmE2NmE5M2ZiYTUwMDM4NWIyMWQwIiwiYXBpU2VjcmV0IjoiNDQ0YTE3NWQtM2I1OC03NDhhLTVlMGEtYTVhZDE2MmRmODJlIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.izSIvaD2udKTs3QRngla1Aw23kZVyoq7Xh23AbPUw1M

{
    "metadata": [
        {
            "title": "clubName",
            "dim": "[OrgUnit.Level4Name]",
            "datatype": "text"
        },
        {
            "title": "club",
            "dim": "[OrgUnit.Level4Code]",
            "datatype": "text",
        },
        {
            "dim": "[UsasSwimTime.SwimEventKey]",
            "datatype": "numeric",
            "filter": {
                "equals": 1
            },
            "panel": "scope"
        },
        {
            "dim": "[OrgUnit.Level3Code]",
            "datatype": "text",
            "filter": {
                "equals": "PN",
            },
            "panel": "scope"
        }
    ],
    "count": 5000
}

###

GET https://www.google.com