###
# get request id json.requestId

POST https://securityapi.usaswimming.org/security/Auth/GetSecurityInfoForToken
Content-Type: application/json

{"toxonomies":[],"appName":"Data","deviceId":0}


###
# get sisense token
# sessionId: ^response.requestId * 13
# deviceId: equals to ^request.deviceId
# hostId: base64(dec(ip address))   // example: base64(dec("0.0.0.0")) = "MA=="

POST https://securityapi.usaswimming.org/security/DataHubAuth/GetSisenseAuthToken
Content-Type: application/json

{"sessionId":1993628,"deviceId":0,"hostId":"MA=="}


###

POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjY0YmE2NmE5M2ZiYTUwMDM4NWIyMWQwIiwiYXBpU2VjcmV0IjoiNDQ0YTE3NWQtM2I1OC03NDhhLTVlMGEtYTVhZDE2MmRmODJlIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.izSIvaD2udKTs3QRngla1Aw23kZVyoq7Xh23AbPUw1M

{
    "metadata": [
        {
            "title": "clubName",
            "dim": "[OrgUnit.Level4Name]",
            "datatype": "text"
        },
        {
            "title": "club",
            "dim": "[OrgUnit.Level4Code]",
            "datatype": "text",
        },
        {
            "dim": "[UsasSwimTime.SwimEventKey]",
            "datatype": "numeric",
            "filter": {
                "equals": 1
            },
            "panel": "scope"
        },
        {
            "dim": "[OrgUnit.Level3Code]",
            "datatype": "text",
            "filter": {
                "equals": "PN",
            },
            "panel": "scope"
        }
    ],
    "count": 5000
}

###

POST https://securityapi.usaswimming.org/security/DataHubAuth/GetSisenseAuthToken
Content-Type: application/json

{"sessionId":1473706,"deviceId":3203989818,"hostId":"MjkzMDA0NzIx","requestUrl":"/datahub/usas/meetsearch/meetsummary"}

###

POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjY0YmE2NmE5M2ZiYTUwMDM4NWIyMWQwIiwiYXBpU2VjcmV0IjoiNDQ0YTE3NWQtM2I1OC03NDhhLTVlMGEtYTVhZDE2MmRmODJlIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.izSIvaD2udKTs3QRngla1Aw23kZVyoq7Xh23AbPUw1M

{
  "metadata": [
    {
      "title": "meet",
      "dim": "[UsasSwimTime.MeetKey]",
      "datatype": "numeric",
      "filter": {
        "members": [
          263665,
          263575,
          261024,
          263503,
          263588,
          262383,
          260319,
          264769,
          262395,
          255126,
          255343,
          261897,
          264748,
          264013,
          263502,
          257602,
          254091,
          248711,
          254161,
          250138,
          257328,
          254582,
          254580,
          257089,
          248894,
          263811,
          249208,
          262456,
          254938,
          260044,
          249185
        ]
      }
    },
    {
      "title": "date",
      "dim": "[SeasonCalendar.CalendarDate (Calendar)]",
      "datatype": "datetime",
      "level": "days",
      "sort": "asc"
    },
    {
      "title": "meetName",
      "dim": "[Meet.MeetName]",
      "datatype": "text"
    }
  ],
  "count": 155
}


###
# list of meets by date range

POST https://usaswimming.sisense.com/api/datasources/Meets/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiMjJhYmIxZGItNzlhYy0zMTQ1LTBjNTItYTU0OGQ5ZjAyOTQ5IiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.0uWonsgKfrpfCDi4GramolaPUNrVrdg-yKAf47s2SQ4

{
  "metadata": [
    {
      "title": "MeetName",
      "dim": "[Meet.MeetName]",
      "datatype": "text"
    },
    {
      "title": "MeetType",
      "dim": "[Meet.MeetType]",
      "datatype": "text"
    },
    {
      "title": "HostLSC",
      "dim": "[OrgUnit.Level3Code]",
      "datatype": "text"
    },
    {
      "title": "HostTeam",
      "dim": "[OrgUnit.Level3Name]",
      "datatype": "text"
    },
    {
      "title": "StartDate",
      "dim": "[Meet.StartDate (Calendar)]",
      "datatype": "datetime",
      "level": "days",
      "sort": "asc",
      "filter": {
        #"from": "1900-01-01T00:00:00",
        #"to": "1980-01-01T00:00:00"
        #"from": "1980-01-01T00:00:00",
        #"to": "2000-01-01T00:00:00"
        "from": "2024-12-01T00:00:00",
        "to": "2024-12-10T00:00:00"
      }
    },
    {
      "title": "EndDate",
      "dim": "[Meet.EndDate (Calendar)]",
      "datatype": "datetime",
      "level": "days"
    },
    {
      "title": "MeetKey",
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric"
    },
    {
      "title": "MeetKey",
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric"
    }
  ],
  "count": 50000
}

###
POST https://usaswimming.sisense.com/api/datasources/Meets/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiMjJhYmIxZGItNzlhYy0zMTQ1LTBjNTItYTU0OGQ5ZjAyOTQ5IiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.0uWonsgKfrpfCDi4GramolaPUNrVrdg-yKAf47s2SQ4

{
  "metadata": [
    {
      "dim": "[OrgUnit.Level4Name]",
      "datatype": "text"
    }
  ],
  "count": 500
}

###
# get meet type by meet key

POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiMjJhYmIxZGItNzlhYy0zMTQ1LTBjNTItYTU0OGQ5ZjAyOTQ5IiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.0uWonsgKfrpfCDi4GramolaPUNrVrdg-yKAf47s2SQ4

{
  "metadata": [
    {
      "title": "SCY",
      "dim": "[Meet.SCY]",
      "datatype": "text"
    },
    {
      "title": "SCM",
      "dim": "[Meet.SCM]",
      "datatype": "text"
    },
    {
      "title": "LCM",
      "dim": "[Meet.LCM]",
      "datatype": "text"
    },
    {
      "title": "Final",
      "dim": "[Meet.Final]",
      "datatype": "numeric"
    },
    {
      "title": "Semi",
      "dim": "[Meet.Semi]",
      "datatype": "numeric"
    },
    {
      "title": "Prelim",
      "dim": "[Meet.Prelim]",
      "datatype": "numeric"
    },
    {
      "title": "MeetKey",
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric",
      "filter": {
        "equals": 252874
      },
      "panel": "scope",
    }
  ],
  "count": 20000,
}


###

POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiMjJhYmIxZGItNzlhYy0zMTQ1LTBjNTItYTU0OGQ5ZjAyOTQ5IiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.0uWonsgKfrpfCDi4GramolaPUNrVrdg-yKAf47s2SQ4

{
  "metadata": [
    {
      "dim": "[UsasSwimTime.UsasSwimTimeKey]",
      "datatype": "numeric",
    },
    {
      "dim": "[UsasSwimTime.PersonKey]",
      "datatype": "numeric",
    },
    {
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric",
      "filter": {
        "equals": 264503
      }
    },
    {
      "dim": "[UsasSwimTime.SwimEventKey]",
      "datatype": "numeric",
    },
    {
      "dim": "[UsasSwimTime.OrgUnitKey]",
      "datatype": "numeric",
    },
    {
      "dim": "[EventCompetitionCategory.TypeName]",
      "datatype": "text"
    }
  ],
  "count": 200,
}
