# docker compose file for build linux devbox
version: "3"
services:
  devbox:
    container_name: linuxbox
    image: xueweihan/devlinux
    # ports:
    #   - 8000-8040:8000-8040
    volumes:
      - ./:/src
      - //var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    command: /bin/bash

#USE
# docker-compose -f linuxbox.yaml up --no-start
# or
# docker create -it --name linuxbox -v "c:\\repos:/src" -v "//var/run/docker.sock:/var/run/docker.sock" xueweihan/devlinux /bin/bash

# docker start -i linuxbox
# docker rm -f linuxbox




# docker run -d --name linuxbox -v "c:\\repos:/src" -v "//var/run/docker.sock:/var/run/docker.sock" xueweihan/devlinux
# docker exec -it linuxbox /bin/bash

