###
# get request id json.requestId

POST https://securityapi.usaswimming.org/security/Auth/GetSecurityInfoForToken
Content-Type: application/json

{"toxonomies":[],"appName":"Data","deviceId":0}


###
# get sisense token
# sessionId: ^response.requestId * 13
# deviceId: equals to ^request.deviceId
# hostId: base64(dec(ip address))   // example: base64(dec("0.0.0.0")) = "MA=="

POST https://securityapi.usaswimming.org/security/DataHubAuth/GetSisenseAuthToken
Content-Type: application/json

{"sessionId":2417701,"deviceId":0,"hostId":"MA=="}


###

POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjY0YmE2NmE5M2ZiYTUwMDM4NWIyMWQwIiwiYXBpU2VjcmV0IjoiNDQ0YTE3NWQtM2I1OC03NDhhLTVlMGEtYTVhZDE2MmRmODJlIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.izSIvaD2udKTs3QRngla1Aw23kZVyoq7Xh23AbPUw1M

{
    "metadata": [
        {
            "title": "clubName",
            "dim": "[OrgUnit.Level4Name]",
            "datatype": "text"
        },
        {
            "title": "club",
            "dim": "[OrgUnit.Level4Code]",
            "datatype": "text",
        },
        {
            "dim": "[UsasSwimTime.SwimEventKey]",
            "datatype": "numeric",
            "filter": {
                "equals": 1
            },
            "panel": "scope"
        },
        {
            "dim": "[OrgUnit.Level3Code]",
            "datatype": "text",
            "filter": {
                "equals": "PN",
            },
            "panel": "scope"
        }
    ],
    "count": 5000
}

###

POST https://securityapi.usaswimming.org/security/DataHubAuth/GetSisenseAuthToken
Content-Type: application/json

{"sessionId":1473706,"deviceId":3203989818,"hostId":"MjkzMDA0NzIx","requestUrl":"/datahub/usas/meetsearch/meetsummary"}

###

POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjY0YmE2NmE5M2ZiYTUwMDM4NWIyMWQwIiwiYXBpU2VjcmV0IjoiNDQ0YTE3NWQtM2I1OC03NDhhLTVlMGEtYTVhZDE2MmRmODJlIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.izSIvaD2udKTs3QRngla1Aw23kZVyoq7Xh23AbPUw1M

{
  "metadata": [
    {
      "title": "meet",
      "dim": "[UsasSwimTime.MeetKey]",
      "datatype": "numeric",
      "filter": {
        "members": [
          263665,
          263575,
          261024,
          263503,
          263588,
          262383,
          260319,
          264769,
          262395,
          255126,
          255343,
          261897,
          264748,
          264013,
          263502,
          257602,
          254091,
          248711,
          254161,
          250138,
          257328,
          254582,
          254580,
          257089,
          248894,
          263811,
          249208,
          262456,
          254938,
          260044,
          249185
        ]
      }
    },
    {
      "title": "date",
      "dim": "[SeasonCalendar.CalendarDate (Calendar)]",
      "datatype": "datetime",
      "level": "days",
      "sort": "asc"
    },
    {
      "title": "meetName",
      "dim": "[Meet.MeetName]",
      "datatype": "text"
    }
  ],
  "count": 155
}


###
# list of meets by date range

POST https://usaswimming.sisense.com/api/datasources/Meets/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiMjJhYmIxZGItNzlhYy0zMTQ1LTBjNTItYTU0OGQ5ZjAyOTQ5IiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.0uWonsgKfrpfCDi4GramolaPUNrVrdg-yKAf47s2SQ4

{
  "metadata": [
    {
      "title": "MeetName",
      "dim": "[Meet.MeetName]",
      "datatype": "text"
    },
    {
      "title": "MeetType",
      "dim": "[Meet.MeetType]",
      "datatype": "text"
    },
    {
      "title": "HostLSC",
      "dim": "[OrgUnit.Level3Code]",
      "datatype": "text"
    },
    {
      "title": "HostTeam",
      "dim": "[OrgUnit.Level3Name]",
      "datatype": "text"
    },
    {
      "title": "StartDate",
      "dim": "[Meet.StartDate (Calendar)]",
      "datatype": "datetime",
      "level": "days",
      "sort": "asc",
      "filter": {
        #"from": "1900-01-01T00:00:00",
        #"to": "1980-01-01T00:00:00"
        #"from": "1980-01-01T00:00:00",
        #"to": "2000-01-01T00:00:00"
        "from": "2024-12-01T00:00:00",
        "to": "2024-12-10T00:00:00"
      }
    },
    {
      "title": "EndDate",
      "dim": "[Meet.EndDate (Calendar)]",
      "datatype": "datetime",
      "level": "days"
    },
    {
      "title": "MeetKey",
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric"
    },
    {
      "title": "MeetKey",
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric"
    }
  ],
  "count": 50000
}

###
POST https://usaswimming.sisense.com/api/datasources/Meets/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiMjJhYmIxZGItNzlhYy0zMTQ1LTBjNTItYTU0OGQ5ZjAyOTQ5IiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.0uWonsgKfrpfCDi4GramolaPUNrVrdg-yKAf47s2SQ4

{
  "metadata": [
    {
      "dim": "[OrgUnit.Level4Name]",
      "datatype": "text"
    }
  ],
  "count": 500
}

###
# get meet type by meet key

POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiYmU5YjRkOWYtOGY5Yi0zYzEwLWI5OTgtMDM4Y2QzMmE3NzAzIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.CJSs3BwZ7TmSToWqA9p50iInJKHvCie5XHKJmgmlOiw

{
  "metadata": [
    {
      "title": "SCY",
      "dim": "[Meet.SCY]",
      "datatype": "text"
    },
    {
      "title": "SCM",
      "dim": "[Meet.SCM]",
      "datatype": "text"
    },
    {
      "title": "LCM",
      "dim": "[Meet.LCM]",
      "datatype": "text"
    },
    {
      "title": "Final",
      "dim": "[Meet.Final]",
      "datatype": "numeric"
    },
    {
      "title": "Semi",
      "dim": "[Meet.Semi]",
      "datatype": "numeric"
    },
    {
      "title": "Prelim",
      "dim": "[Meet.Prelim]",
      "datatype": "numeric"
    },
    {
      "title": "MeetKey",
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric",
      "filter": {
        "equals": 252874
      },
      "panel": "scope",
    }
  ],
  "count": 20000,
}


###
# event table 

POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiYmU5YjRkOWYtOGY5Yi0zYzEwLWI5OTgtMDM4Y2QzMmE3NzAzIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.CJSs3BwZ7TmSToWqA9p50iInJKHvCie5XHKJmgmlOiw

{
  "metadata": [
    {
      "dim": "[UsasSwimTime.UsasSwimTimeKey]",
      "datatype": "numeric",
    },
    {
      "dim": "[UsasSwimTime.PersonKey]",
      "datatype": "numeric",
    },
    {
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric",
      "filter": {
        "equals": 264503
      }
    },
    {
      "dim": "[UsasSwimTime.SwimEventKey]",
      "datatype": "numeric",
    },
    {
      "dim": "[UsasSwimTime.OrgUnitKey]",
      "datatype": "numeric",
    },
    {
      "dim": "[EventCompetitionCategory.TypeCode]",
      "datatype": "numeric"
    },
    {
      "dim": "[Meet.Final]",
      "datatype": "numeric"
    },
    {
      "dim": "[Meet.Semi]",
      "datatype": "numeric"
    },
    {
      "dim": "[Meet.Prelim]",
      "datatype": "numeric"
    },
    {
      "dim": "[Age.AgeGroup1]",
      "datatype": "text",
    },
    {
                            "dim": "[Session.SessionName]",
                            "datatype": "text",
    },
        {
                            "dim": "[Session.SessionKey]",
                            "datatype": "text",
    }

  ],
  "count": 200,
}

# total swim time count = 168_201_504
# {
#   "metadata": [
#     {
#       "agg": "count",
#       "dim": "[UsasSwimTime.UsasSwimTimeKey]",
#       "datatype": "numeric",
#     }
#   ],
#   "count": 1,
# }

###
# get all lsc in a meet

POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiMDhhYTVlYmMtMmI3Ny05M2IyLTUwNDAtOTE0ZGUwYTBiMmUzIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.wimscCV-zoU9uhR3X0qYYVEvffsdfw62u9v4m3ZV19U

{
  "metadata": [
    {
      "dim": "[OrgUnit.Level3Code]",
      "datatype": "text",
    },
    {
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric",
      "filter": {
        "equals": 254611
      }
    },
  ],
  "count": 200
}

###
# imx/imr single

POST https://usaswimming.sisense.com/api/datasources/Club Performance Elasticube/jaql
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiZDBhYTNhYTItYmQxZS1mNmY2LTNmN2ItZjhmY2Y1MGIzN2ZlIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.h8Mts3Y9ekmCKiUB_4bspnWOHGaOTuSjItm7qd7st6I

{
  "metadata": [
    {
      "title": "Event",
      "dim": "[SwimEvent.SwimEventKey]",
      "datatype": "numeric",
    },
    {
      "title": "Event",
      "dim": "[SwimEvent.EventCode]",
      "datatype": "text"
    },
    {
      "title": "Meet",
      "dim": "[Meet.MeetKey]",
      "datatype": "numeric",
    },
    {
      "title": "Meet",
      "dim": "[Meet.MeetName]",
      "datatype": "text"
    },
    {
      "title": "Swim Date",
      "dim": "[ImxDetail.SwimDate (Calendar)]",
      "datatype": "datetime",
      "level": "days"
    },
    {
      "title": "Swim Time",
      "dim": "[ImxDetail.SwimTimeFormatted]",
      "datatype": "text"
    },
    {
      "title": "Score",
      "dim": "[ImxDetail.IMXPoints]",
      "datatype": "numeric",
      "sort": "desc"
    },
    {
      "title": "ImxSummaryKey",
      "dim": "[ImxSummary.ImxSummaryKey]",
      "datatype": "numeric",
      "filter": {
        # "members": [4069244, 4241501, 4069212, 4241509]
        # "members": [4158643, 4283143, 4283193, 4158634]
        "members": [4258075, 4158643]
      },
    }
  ],
  "count": 500
}

###### 
# IMX/IMR ranking

POST https://usaswimming.sisense.com/api/datasources/Club Performance Elasticube/jaql
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiZDBhYTNhYTItYmQxZS1mNmY2LTNmN2ItZjhmY2Y1MGIzN2ZlIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.h8Mts3Y9ekmCKiUB_4bspnWOHGaOTuSjItm7qd7st6I

{
  "metadata": [
    {
      "title": "lsc",
      "dim": "[OrgUnit.Level3Code]",
      "datatype": "text"
    },
    {
        "title": "pkey",
        "dim": "[Person.personKey]",
        "datatype": "numeric"
    },
    {
      "title": "name",
      "dim": "[Person.fullname]",
      "datatype": "text"
    },
    {
      "title": "age",
      "dim": "[Age.IMXAgeRange]",
      "datatype": "text",
      "filter": {
        "members": ["10", "9"]
      }
    },
    {
      "title": "lsc",
      "dim": "[OrgUnit.Level3Code]",
      "datatype": "text",
      "filter": {
        "equals": "PN"
      }
    },
    {
      "title": "clubName",
      "dim": "[OrgUnit.Level4Name]",
      "datatype": "text"
    },
    {
      "title": "score",
      "dim": "[ImxSummary.ImxPoints]",
      "datatype": "numeric",
      "sort": "desc"
    },
    {
      "title": "natiRank",
      "dim": "[ImxSummary.NationalRank]",
      "datatype": "numeric"
    },
    {
      "title": "zoneRank",
      "dim": "[ImxSummary.ZoneRank]",
      "datatype": "numeric"
    },
    {
      "title": "lscRank",
      "dim": "[ImxSummary.LscRank]",
      "datatype": "numeric"
    },
    {
      "title": "sumaryKey",
      "dim": "[ImxSummary.ImxSummaryKey]",
      "datatype": "numeric"
    },
    {
      "title": "imxType",
      "dim": "[ImxSeason.ImxType]",
      "datatype": "text",
      "filter": {
        "equals": "IMR"
      },
      "panel": "scope"
    },
    {
      "title": "gender",
      "dim": "[CompetitionCategory.CompetitionCategoryKey]",
      "datatype": "numeric",
      "filter": {
        "equals": 2
      },
      "panel": "scope"
    },
    {
      "dim": "[ImxSeason.ImxSeasonName]",
      "datatype": "text",
      "filter": {
        "members": [
          # "SCY 2024-2025",
          # "SCY 2023-2024",
          "SCY 2024-2025 (IMR)",
          "SCY 2023-2024 (IMR)"
        ]
      },
      "panel": "scope"
    }
  ],
  "count": 10
}


###
# power point

GET https://commonapi.usaswimming.org/swims/DataHub/PowerPointCalculator?filters={"swimmerAge":10,"swimEventKey":11,"eventCompetitionCategory":"M","swimTime":"00:00:38.70"}
Authorization: Bearer undefined

###
# testing

POST https://usaswimming.sisense.com/api/datasources/Public Person Search/jaql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiZTgwMGM3MDYtOGJiMy0yMWM3LWIzY2UtMmExMDkwZmFlNzIyIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.QmD5DJe491URBKuNuXnADE-zaytc7vBPQYQKQh48hak

{
  "metadata": [
    {
      "title": "name",
      "dim": "[Persons.FullName]",
      "filter": {
        "contains": "alexander"
      }
    },
    {
      "title": "name",
      "dim": "[Persons.FullName]",
      "filter": {
        "contains": "han"
      },
      "panel": "scope"
    },
    {
      "title": "age",
      "dim": "[Persons.Age]",
      "filter": {
        "to": 18
      },
      "sort": "asc"
    },
    {
      "title": "clubName",
      "dim": "[Persons.ClubName]"
    },
    {
      "title": "lsc",
      "dim": "[Persons.LscCode]"
    },
    {
      "title": "pkey",
      "dim": "[Persons.PersonKey]"
    }
  ],
  "count": 5000
}


                    # {
                    #     "title": "clubName",
                    #     "dim": "[OrgUnit.Level4Name]",
                    #     "datatype": "text"
                    # },
                    # {
                    #     "agg": "count",
                    #     "dim": "[OrgUnit.Level4Code]",
                    #     "datatype": "text",
                    # },
###
POST https://usaswimming.sisense.com/api/datasources/USA Swimming Times Elasticube/jaql
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRhZjE4MGY5Nzg1MmIwMDJkZTU1ZDhkIiwiYXBpU2VjcmV0IjoiNjM4MDllMTUtMDI2MC02MTFjLWUzY2MtMmU4N2ZmNjU5NDMwIiwiYWxsb3dlZFRlbmFudHMiOlsiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIl0sInRlbmFudElkIjoiNjRhYzE5ZTEwZTkxNzgwMDFiYzM5YmVhIn0.xwywApsNy8q1H7TPg96Z2Y0wFz_TLxM4c2nBiVgSI54

{
  "metadata": [
    {
      "dim": "[UsasSwimTime.EventCompetitionCategoryKey]",
      "datatype": "numeric"
    },
    {
      "dim": "[EventCompetitionCategory.TypeCode]",
      "datatype": "numeric"
    },
    {
      "dim": "[EventCompetitionCategory.TypeName]",
      "datatype": "numeric"
    },
  ],
  "count": 100,
}