name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go 1.22.0
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.0

    - name: Go Build
      run: go build -a -v -o ./bin/ .

    - name: Go Test
      run: go test -v ./...

    - name: Bump version and push tag
      id: version_tag
      uses: anothrNick/github-tag-action@1.66.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Docker build and push
      run: |
        # tag=$(git describe --tags)
        tag=${{ steps.version_tag.outputs.new_tag }}
        tag=${tag#"v"}
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/home-server:$tag .
        docker push ${{ secrets.DOCKER_USERNAME }}/home-server:$tag
        docker logout
