name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set up Go 1.22.0
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: 1.22.0

    # - name: Go Build
    #   run: go build -a -v -o ./bin/ .

    # - name: Go Test
    #   run: go test -v ./...

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
    #   with:
    #     images: my-docker-hub-namespace/my-docker-hub-repository

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
    - name: Docker build and push
      run: |
        tag=$(git describe --tags)
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/home-server:$tag .
        docker push ${{ secrets.DOCKER_USERNAME }}/home-server:$tag


    # - name: Login to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Build and push
    #   run: |
    #     docker build . -t torusdev1.azurecr.io/goapp
    #     docker push torusdev1.azurecr.io/goapp
