name: Build go app and push to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.0

    - name: Go Build
      run: go build -v .

    - name: Go Test
      run: go test -v ./..

    # - name: Login to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Build and push
    #   run: |
    #     docker build . -t torusdev1.azurecr.io/goapp
    #     docker push torusdev1.azurecr.io/goapp