name: Publish

on:
  # Automatic trigger when pushing tags
  push:
    tags:
      - 'v*'

  # # Manual trigger from the UI
  # workflow_dispatch:
  #   inputs:
  #     message:
  #       description: 'Publish description'

  # # Dependency to a forking workflow
  # workflow_run:
  #   workflows: ["Build"]
  #   type:
  #   - complete

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build docker
      run: |
        docker build -t home-server .
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo ${GITHUB_REF}
        echo ${GITHUB_REF#refs/*/}
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{ github.ref_name }}"
