name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

    - name: show env
      run: echo hello world ${{ github.event.inputs.tag }}

    - name: Checkout code
      uses: actions/checkout@v4

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name homeserverdata --auth-mode key --overwrite true -d 'data' -s 'data' --pattern '*.json'
          az storage blob upload-batch --account-name homeserverdata --auth-mode key --overwrite true -d 'swim-html' -s 'swim/html' --pattern '*.html'

    - name: logout
      run: az logout
      if: always()
