name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract tag
      id: extract_tag
      run: |
        tag=${GITHUB_REF#refs/tags/v}
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo $tag

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name homeserverdata --auth-mode key --overwrite true -d 'data' -s 'data' --pattern '*.json'
          az storage blob upload-batch --account-name homeserverdata --auth-mode key --overwrite true -d 'swim-html' -s 'swim/html' --pattern '*.html'
          az storage blob upload-batch --account-name homeserverdata --auth-mode key --overwrite true -d 'file-html' -s 'file/html' --pattern '*.html'
          az storage blob upload-batch --account-name homeserverdata --auth-mode key --overwrite true -d 'file-html' -s 'file/html' --pattern '*.json'
          az storage blob upload-batch --account-name homeserverdata --auth-mode key --overwrite true -d 'file-files' -s 'file/files'
          az storage blob upload-batch --account-name usaswimming --auth-mode key --overwrite true -d 'meet-cut' -s 'file/files/meet-cut'

    - name: Deploy web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'swimrank'
        # slot-name: 'production'
        images: xueweihan/home-server:${{ steps.extract_tag.outputs.tag }}

    - name: logout
      run: az logout
      if: always()
